### PR TITLE
Feature: operations

### PR DESCRIPTION
**Pull request by vadymmarkov**
@zenangst @RamonGilabert @onmyway133 
This feature introduces operations instead of tasks in `Malibu` meaning that `NSOperationQueue` is used to execute/cancel requests. That makes it easier to manage request lifetime and concurrency.

1) When you create a new networking instance there is an optional argument to specify `operationKind` which could be `Sync`, `Async` or `Limited`:

```swift
let networking = Networking(operationKind: .Sync) // requests will be executed one after another
```

2) Small addition to `Mock`, now it's possible to specify a delay in the `init`.

### CODE REVIEW

**Comment by zenangst** [comment]
I like this!

**Comment by vadymmarkov** [comment]
If it works for you @zenangst we can merge it and make a new release 😄

**Comment by RamonGilabert** [comment]
Such [WIP] tho.

**Comment by RamonGilabert** [comment]
Free 🍬.

maxresdefault

**Comment by vadymmarkov** [comment]
@RamonGilabert Let's hope it works 😄

**Pull request merged**
